# Generated by Django 4.1.7 on 2023-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_competence_user_competence"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ex", "expert"), ("st", "student")], max_length=2, null=True
            ),
        ),
    ]
