# Generated by Django 4.1.7 on 2023-04-02 13:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_user_birth_date_user_name_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="education_format",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("ft", "full-time"), ("on", "online")], max_length=2, null=True
            ),
        ),
    ]
