# Generated by Django 4.1.7 on 2023-04-08 23:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_user_education_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="education_format",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("ft", "full-time"), ("on", "online")], max_length=6, null=True
            ),
        ),
    ]
