# Generated by Django 4.1.7 on 2023-04-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0006_alter_user_education_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="education_format",
        ),
        migrations.AddField(
            model_name="user",
            name="education_stage",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
