# Generated by Django 4.1.7 on 2023-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_remove_user_education_format_user_education_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
