# Generated by Django 4.1.7 on 2023-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_self",
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="course_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="learning_trajectory",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
