# Generated by Django 4.1.7 on 2023-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0009_user_about_self_user_course_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.TextField(null=True),
        ),
    ]
