# Generated by Django 4.1.7 on 2023-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0010_remove_user_surname_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
